In [3]:
import numpy as np

In [17]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [18]:
array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]], dtype=np.int64)
array


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [49]:
array = np.random.rand(5,6).astype(np.int64)
array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [55]:
onceArray = np.abs([5, 5], dtype=np.float64)
print(onceArray)

[5. 5.]


In [ ]:
for i, v in enumerate(np.arange(3, 3*10+1, 3)):
    print(f"3 * {i+1} = {v}")

np.unique([1, 2, 2, 3, 4, 4, 5])
# Add elements to the array
array = np.array(np.unique([1, 2, 2, 3, 4, 4, 5.5]), dtype=np.int64)
array

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30


array([1. , 2. , 3. , 4. , 5.5])